### ISSUE TITLE
Refactor Proyect

### ISSUE THREAD

**Issue by eliseo-arevalo** [SciProgrammist/Proyecto_Catedra_LIC01T#1]
Hola, soy Eliseo Arévalo, me interesa crear un proyecto - mapa de el salvador nueva distribución de municipios y quiero invitarte

**Comment by eliseo-arevalo** [comment]
@SciProgrammist agradecería me respondas si deseas participar, planeo hacer con tecnologías javascript pero estoy abierto a opciones

**Comment by eliseo-arevalo** [comment]
@MariaTorres0  @i-ashy @SomeRandomCatholic  también estan invitados

**Comment by SciProgrammist** [comment]
Hola! Ahorita estoy ocupado con otros proyectos, y mis compañeros estan trabajando en sus materias, podes hacer una nueva branch si deseas no hay problema 😁

**Comment by eliseo-arevalo** [comment]
Ah okay, no no, crearía una APi para servir los datos y los consumiría en el front con React, pero gracias por contestar
